global_costmap:
  plugins:
    - {name: obstacles,         type: "costmap_2d::ObstacleLayer"}
    - {name: inflation,         type: "costmap_2d::InflationLayer"}

  update_frequency: 10.0
  publish_frequency: 10.0

  global_frame: map
  robot_base_frame: base_link

  rolling_window: true
  width: 30.0
  height: 30.0
  resolution: 0.2

  transform_tolerance: 1.0

  footprint: [[0.55,   0.4],
              [-0.55,  0.4],
              [-0.55, -0.4],
              [0.55,-0.4]]

  inflation:
      inflation_radius: 1.0
      cost_scaling_factor: 1.2

  obstacles:
    observation_source: base_scan
    base_scan: {data_type: LaserScan, sensor_frame: /base_link, clearing: true, marking: true, topic: /scan}
